import EmptyState from "../components/EmptyState";

export default function ArtifactsPage() {
  return (
    <div>
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Artifacts</h2>
      <EmptyState
        title="No Artifacts"
        description="Artifacts generated by the Hub will appear here. You'll be able to view and manage them in a timeline."
      />
    </div>
  );
}
